// This file is generated by Slice Machine. Update with care!

import GaleriaZdjec from './GaleriaZdjec';
import PelnaSzerokosc from './PelnaSzerokosc';
import PodgladStrony from './PodgladStrony';
import SekcjaTekst from './SekcjaTekst';

export {
	GaleriaZdjec,
	PelnaSzerokosc,
	PodgladStrony,
	SekcjaTekst,
};

export const components = {
	galeria_zdjec: GaleriaZdjec,
	pelna_szerokosc: PelnaSzerokosc,
	podglad_strony: PodgladStrony,
	sekcja_tekst: SekcjaTekst,
};
