// This file is generated by Slice Machine. Update with care!

import Brand from './Brand';
import GaleriaBrandow from './GaleriaBrandow';
import GaleriaZdjec from './GaleriaZdjec';
import PelnaSzerokosc from './PelnaSzerokosc';
import PodgladStrony from './PodgladStrony';
import SekcjaTekst from './SekcjaTekst';

export {
	Brand,
	GaleriaBrandow,
	GaleriaZdjec,
	PelnaSzerokosc,
	PodgladStrony,
	SekcjaTekst,
};

export const components = {
	brand: Brand,
	galeria_brandow: GaleriaBrandow,
	galeria_zdjec: GaleriaZdjec,
	pelna_szerokosc: PelnaSzerokosc,
	podglad_strony: PodgladStrony,
	sekcja_tekst: SekcjaTekst,
};
